markdown:         rdiscount
pygments:         true
paginate:         5

title:            Yuki Lau's Blog
url:              http://yuki-lau.github.io
feed:             /atom.xml
author:
    name:         YukiLau
    email:        sasa-yoyo@163.com
    description:  "A Running Girl and Coding Girl."

about:            "说点啥."
follow:
    email:        sasa-yoyo@163.com
    github:       https://github.com/yuki-lau
    weibo:        http://weibo.com/yuuuuuki
description:      Yuki Lau's Blog which records her life, study and working.

indexContent:     true


style:            /css/style.css
blogName:         YukiLau 
blogDesc:         Running Girl
favicon:          /images/style/favicon.ico
theme:            blue

disqus:           yukilau

copyright:        Copyright © 2013-2014 <a href="http://yuki-lau.github.io" target="_blank">Yuki Lau</a> All rights reserved.<br/> 
test:             ok
